### ISSUE TITLE
phpmyadmin doesn't work

### ISSUE THREAD

**Issue by markolofsen** [niiknow/vestacp#68] opened 2018-11-19 18:11 UTC
phpmyadmin doesn't work.
also when I trying to add new mysql db got an error: `Error: Connection to localhost failed`

when I execute command 'Error: mysqld restart failed' receiving this error 
```
v-restart-service mysqld
Error: mysqld restart failed
```

**My conf:**
```
#!/bin/sh

# re-enable phpmyadmin and phppgadmin
rsync -a /etc/apache2/conf-d/php*.conf /etc/apache2/conf.d

# required startup and of course vesta
cd /etc/init.d/
./disable-transparent-hugepages defaults

# the 5 services below are enabled to support mininum default backup job
./apache2 start
./mysql start

# delete defult postgres admindb if not use, then comment out the line below
#./postgresql start
./nginx start
./vesta start

# && ./exim4 start \
# && ./dovecot start \
# && ./clamav-daemon start \
# && ./spamassassin start \
# && ./php7.1-fpm start \
# && ./fail2ban start \ # -- only if you run with: --cap-add=NET_ADMIN --cap-add=NET_RAW

```

**Comment by noogen** [comment] 2018-11-19 21:20
Are you using latest, if not, what version are you using?  I'm asking because there was an issue (with changes in Vesta install script) in a previous version which I've patched in #57 and #53

Also, for security reason, it is disabled by default.  To re-enable service, restore the configs from backup folder /etc/apache2/conf-d:
```
rsync -a /etc/apache2/conf-d/phpmy*.conf /etc/apache2/conf.d
```

Please use latest version: 1.5.0 (image id f287737ab12a)

If your latest version "CREATED" is older than 11 days ago, then it's not the latest:
```
docker images
```

**Comment by markolofsen** [comment] 2018-11-20 00:10
Yes, I'm using last version.

**Comment by noogen** [comment] 2018-11-20 00:19
Is this an upgrade or a fresh install?

**Comment by noogen** [comment] 2018-11-20 00:55
Confirming bug, install script from upstream (Vesta) recently changed separating mysql and postgresql password: https://github.com/serghey-rodin/vesta/commit/1557f9bc8cbdb349a83bce96093b1717b36cf5cd#diff-df8da0c91e9086454c60cd468849630d 

Similar issue was also the cause of previous bug you reported result in my monkey patching.  I'm removing my patch and will push out shortly.

**Comment by noogen** [comment] 2018-11-20 05:59
This should be fixed in latest (1.5.1), let me know if it's still an issue.  Thanks.

**Comment by markolofsen** [comment] 2018-11-20 12:18
@noogen It's work. Please add in your readme `docker restart $container` after changing `/home/admin/bin/my-startup.sh` because it's not obvious

**Comment by noogen** [comment] 2018-11-20 15:37
Doc updated.

**Closed as completed by noogen** 2018-11-20 15:37 UTC
Labels: bug
